### PR TITLE
Add value-category-cheatsheet link

### PR DESCRIPTION
**Pull request by jeaye**

### CODE REVIEW

**Comment by jeaye** [comment]
If there's no interest in this, let's close it. Otherwise, let's merge please.

**Comment by mredolatti-devspark** [comment]
Looks nice!

**Comment by mredolatti** [comment]
Looks nice!

**Comment by jeaye** [comment]
Bump, it looks nice, but will it merge?

**Comment by ccding** [comment]
can you change the link to the repo webpage instead of the PDF file?

**Comment by jeaye** [comment]
Done.

**Pull request merged**
